/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishastanesi;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class Giris extends javax.swing.JFrame {
    private Connection conn = null; 
    private String url = "jdbc:mysql://localhost:3306/";
    private String dbName = "hastane"; 
    private String driver = "com.mysql.jdbc.Driver";
    private String userName = "root"; 
    private String password = "anadolu232"; 
    private ResultSet res;  
    /**
     * Creates new form Giris
     */
    public Giris() {
        initComponents(); 

        Statement st; 
        try {
            st = baglantiAc(); 
            res = st.executeQuery("SELECT * FROM  yetkiligiris"); 
        } catch (Exception ex) {
            
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
        }
    }
    public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);//bağlantı açılıyor           
        return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        //return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        //return conn.createStatement();
    }

    public void baglantiKapat() throws Exception {
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yadtext = new javax.swing.JTextField();
        sifrelabel = new javax.swing.JLabel();
        ygiris = new javax.swing.JButton();
        ysifretext = new javax.swing.JPasswordField();
        yetkili = new javax.swing.JLabel();
        yetkililabel = new javax.swing.JLabel();
        hbuton = new javax.swing.JButton();
        bayrak = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        bakan = new javax.swing.JLabel();
        çıkış = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burdur Ağız Diş Sağlığı Merkezi");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        yadtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(yadtext);
        yadtext.setBounds(200, 140, 130, 30);

        sifrelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifrelabel.setText("Şifre:");
        jPanel1.add(sifrelabel);
        sifrelabel.setBounds(130, 200, 36, 20);

        ygiris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/doktor.png"))); // NOI18N
        ygiris.setText("Doktor Girişi");
        ygiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ygirisActionPerformed(evt);
            }
        });
        jPanel1.add(ygiris);
        ygiris.setBounds(9, 270, 160, 50);

        ysifretext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(ysifretext);
        ysifretext.setBounds(200, 200, 130, 30);

        yetkili.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        yetkili.setText("Giriş");
        jPanel1.add(yetkili);
        yetkili.setBounds(210, 80, 51, 20);

        yetkililabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yetkililabel.setText("Yetkili Adı:");
        jPanel1.add(yetkililabel);
        yetkililabel.setBounds(90, 140, 71, 20);

        hbuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/yetkili.jpg"))); // NOI18N
        hbuton.setText("Yetkili Girişi");
        hbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbutonActionPerformed(evt);
            }
        });
        jPanel1.add(hbuton);
        hbuton.setBounds(180, 270, 150, 50);

        bayrak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N
        jPanel1.add(bayrak);
        bayrak.setBounds(0, 0, 45, 45);

        tittle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        tittle.setText("Hastane Randevu Sistemi");
        jPanel1.add(tittle);
        tittle.setBounds(110, 20, 261, 22);

        bakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N
        jPanel1.add(bakan);
        bakan.setBounds(435, 0, 45, 45);

        çıkış.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/çkış.png"))); // NOI18N
        çıkış.setText("Çıkış");
        çıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çıkışActionPerformed(evt);
            }
        });
        jPanel1.add(çıkış);
        çıkış.setBounds(350, 270, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ygirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ygirisActionPerformed
    String user = yadtext.getText();
    String pass = String.valueOf(ysifretext.getPassword());
    
        try {
            while(res.next()){
                String kull ;
                String sfre ;
                kull=res.getString("Yetkili");
                sfre=res.getString("Sifre");
                if (user.equals(kull) && pass.equals(sfre)) {
                doktorsayfa frame;
                frame =new doktorsayfa();
                frame.setVisible(true);
                dispose();
      } else {
         JOptionPane.showMessageDialog(null, "Giriş Başarısız");
      }
            }   } 
        catch (SQLException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ygirisActionPerformed

    private void hbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbutonActionPerformed
    hasta frame;
    frame= new hasta();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_hbutonActionPerformed

    private void çıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çıkışActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_çıkışActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakan;
    private javax.swing.JLabel bayrak;
    private javax.swing.JButton hbuton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sifrelabel;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField yadtext;
    private javax.swing.JLabel yetkili;
    private javax.swing.JLabel yetkililabel;
    private javax.swing.JButton ygiris;
    private javax.swing.JPasswordField ysifretext;
    private javax.swing.JButton çıkış;
    // End of variables declaration//GEN-END:variables
}
