/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishastanesi;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class hasta extends javax.swing.JFrame {
    private Connection conn = null; 
    private String url = "jdbc:mysql://localhost:3306/";
    private String dbName = "hastane"; 
    private String driver = "com.mysql.jdbc.Driver";
    private String userName = "root"; 
    private String password = "anadolu232"; 
    private ResultSet res; 
    /**
     * Creates new form hasta
     */
    public hasta() {
        initComponents();
        Statement st; 
        try {
            st = baglantiAc(); 
            res = st.executeQuery("SELECT * FROM  hastagiris"); 
        } catch (Exception ex) {
            
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
        }
    }
     public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);//bağlantı açılıyor           
        return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        //return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        //return conn.createStatement();
    }

    public void baglantiKapat() throws Exception {
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittlelabel = new javax.swing.JLabel();
        bayrak = new javax.swing.JLabel();
        bakanlik = new javax.swing.JLabel();
        tclabel = new javax.swing.JLabel();
        sifretext = new javax.swing.JLabel();
        tctext = new javax.swing.JTextField();
        passtext = new javax.swing.JPasswordField();
        girisbuton = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        oturum = new javax.swing.JButton();
        geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yerkili Giriş Ekranı");

        tittlelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tittlelabel.setText("Yetkili Giriş Ekranı");

        bayrak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N

        bakanlik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N

        tclabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tclabel.setText("T.C Kimlik Numarası:");

        sifretext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifretext.setText("Şifre:");

        girisbuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/giris.png"))); // NOI18N
        girisbuton.setText("Giriş");
        girisbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisbutonActionPerformed(evt);
            }
        });

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/çkış.png"))); // NOI18N
        cikis.setText("Çıkış");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        oturum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/oturum.jpg"))); // NOI18N
        oturum.setText("Oturumu Kapat");
        oturum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oturumActionPerformed(evt);
            }
        });

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geri2.png"))); // NOI18N
        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bayrak, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(geri)
                .addGap(39, 39, 39)
                .addComponent(tittlelabel)
                .addGap(37, 37, 37)
                .addComponent(bakanlik))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(girisbuton)
                .addGap(29, 29, 29)
                .addComponent(cikis)
                .addGap(7, 7, 7)
                .addComponent(oturum))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(tclabel)
                        .addGap(33, 33, 33)
                        .addComponent(tctext, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(sifretext)
                        .addGap(33, 33, 33)
                        .addComponent(passtext)))
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bayrak)
                    .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tittlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakanlik))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tclabel)
                    .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifretext)
                    .addComponent(passtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(girisbuton)
                    .addComponent(cikis)
                    .addComponent(oturum)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisbutonActionPerformed
    String user = tctext.getText();
    String pass = String.valueOf(passtext.getPassword());
    
        try {
            while(res.next()){
                String kull ;
                String sfre ;
                kull=res.getString("TC");
                sfre=res.getString("SIFRE");
                if (user.equals(kull) && pass.equals(sfre)) {
                randevu frame;
                frame=new randevu();
                frame.setVisible(true);
                /*tablo frame2;
                frame2=new tablo();
                frame2.setVisible(true);*/
                dispose();
      } else {
         JOptionPane.showMessageDialog(null, "Giriş Başarısız");
      }
            }   } 
        catch (SQLException ex) {
            Logger.getLogger(hasta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_girisbutonActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cikisActionPerformed

    private void oturumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oturumActionPerformed
    Giris frame;
    frame=new Giris();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_oturumActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
    Giris frame;
    frame=new Giris();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakanlik;
    private javax.swing.JLabel bayrak;
    private javax.swing.JButton cikis;
    private javax.swing.JButton geri;
    private javax.swing.JButton girisbuton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton oturum;
    private javax.swing.JPasswordField passtext;
    private javax.swing.JLabel sifretext;
    private javax.swing.JLabel tclabel;
    private javax.swing.JTextField tctext;
    private javax.swing.JLabel tittlelabel;
    // End of variables declaration//GEN-END:variables
}
