package dishastanesi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class sifredegis extends javax.swing.JFrame {
    private Connection conn = null; 
    private String url = "jdbc:mysql://localhost:3306/";
    private String dbName = "hastane"; 
    private String driver = "com.mysql.jdbc.Driver";
    private String userName = "root";
    private String password = "anadolu232"; 
    private ResultSet res; 
    /**
     * Creates new form giris
     */
    /**
     * Creates new form sifredegis
     */
       public sifredegis() {
        initComponents(); 

        Statement st; 
        try {
            st = baglantiAc(); 
            res = st.executeQuery("SELECT * FROM  hastagiris"); 
        } catch (Exception ex) {
            
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
        }

   
           
    }

    public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);//bağlantı açılıyor           
        return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        //return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        //return conn.createStatement();
    }

    public void baglantiKapat() throws Exception {
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sifrelabel = new javax.swing.JLabel();
        sifre = new javax.swing.JTextField();
        kdegis = new javax.swing.JButton();
        geri = new javax.swing.JButton();
        anasayfabuton = new javax.swing.JButton();
        tittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yetkili Şifre Değiştirme Ekranı");

        sifrelabel.setText("Sifre:");

        kdegis.setText("Şifreyi Değiştir");
        kdegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdegisActionPerformed(evt);
            }
        });

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geri2.png"))); // NOI18N
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        anasayfabuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/ev2.png"))); // NOI18N
        anasayfabuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfabutonActionPerformed(evt);
            }
        });

        tittle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        tittle.setText("ŞİFRE DEĞİŞTİRME İŞLEMLERİ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(tittle)
                .addGap(4, 4, 4)
                .addComponent(anasayfabuton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(sifrelabel)
                .addGap(4, 4, 4)
                .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(kdegis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geri)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(tittle))
                    .addComponent(anasayfabuton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(sifrelabel))
                    .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kdegis)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kdegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdegisActionPerformed
        try {
            while(res.next()){
                
                res.updateString("SIFRE", sifre.getText());
                res.updateRow();
            }} 
        catch (SQLException ex) {
            Logger.getLogger(sifredegis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kdegisActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
                randevu frame;
                frame=new randevu();
                frame.setVisible(true);
                dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_geriActionPerformed

    private void anasayfabutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfabutonActionPerformed
    hasta frame ;
    frame=new hasta();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_anasayfabutonActionPerformed
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sifredegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sifredegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sifredegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sifredegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new sifredegis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfabuton;
    private javax.swing.JButton geri;
    private javax.swing.JButton kdegis;
    private javax.swing.JTextField sifre;
    private javax.swing.JLabel sifrelabel;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
