/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diş.hastanesi.randevu.takip.programı;

/**
 *
 * @author Ahmed
 */
public class doktorsayfa extends javax.swing.JFrame {

    /**
     * Creates new form doktorsayfa
     */
    public doktorsayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sıradaki = new javax.swing.JButton();
        teshis = new javax.swing.JButton();
        sifre = new javax.swing.JButton();
        geri = new javax.swing.JButton();
        bayrak = new javax.swing.JLabel();
        bakna = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doktor İşlemleri");

        jPanel1.setLayout(null);

        sıradaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/tablo.jpg"))); // NOI18N
        sıradaki.setText("Sıradaki Hastaları Göster");
        sıradaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sıradakiActionPerformed(evt);
            }
        });
        jPanel1.add(sıradaki);
        sıradaki.setBounds(110, 210, 199, 53);

        teshis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/hasta.jpg"))); // NOI18N
        teshis.setText("Teşhis");
        teshis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teshisActionPerformed(evt);
            }
        });
        jPanel1.add(teshis);
        teshis.setBounds(110, 140, 200, 53);

        sifre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/sifre.jpg"))); // NOI18N
        sifre.setText("Şifre İşlemleri");
        sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreActionPerformed(evt);
            }
        });
        jPanel1.add(sifre);
        sifre.setBounds(110, 280, 200, 53);

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geri2.png"))); // NOI18N
        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });
        jPanel1.add(geri);
        geri.setBounds(0, 353, 100, 50);

        bayrak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N
        jPanel1.add(bayrak);
        bayrak.setBounds(0, 0, 50, 50);

        bakna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N
        jPanel1.add(bakna);
        bakna.setBounds(399, 0, 45, 50);

        tittle.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 0, 0));
        tittle.setText("Doktor İşlemleri Ekranı");
        jPanel1.add(tittle);
        tittle.setBounds(130, 10, 190, 17);

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/makü.png"))); // NOI18N
        jPanel1.add(bg1);
        bg1.setBounds(0, 0, 220, 200);

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/makü.png"))); // NOI18N
        jPanel1.add(bg2);
        bg2.setBounds(220, 0, 230, 200);

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/makü.png"))); // NOI18N
        jPanel1.add(bg3);
        bg3.setBounds(0, 200, 220, 200);

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/makü.png"))); // NOI18N
        jPanel1.add(bg4);
        bg4.setBounds(220, 200, 230, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teshisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teshisActionPerformed
    teshis framei;
    framei=new teshis();
    framei.setVisible(true);
    dispose();
    }//GEN-LAST:event_teshisActionPerformed

    private void sıradakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sıradakiActionPerformed
    tablo frame;
    frame= new tablo();
    frame.setVisible(true);
    }//GEN-LAST:event_sıradakiActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
    Giris frame;
    frame =new Giris();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_geriActionPerformed

    private void sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreActionPerformed
    sifre frame;
    frame =new sifre();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_sifreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktorsayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktorsayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktorsayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktorsayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktorsayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakna;
    private javax.swing.JLabel bayrak;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JButton geri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sifre;
    private javax.swing.JButton sıradaki;
    private javax.swing.JButton teshis;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
