/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diş.hastanesi.randevu.takip.programı;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class ekle extends javax.swing.JFrame {
    private Connection conn = null; 
    private String url = "jdbc:mysql://localhost:3306/";
    private String dbName = "hastane"; 
    private String driver = "com.mysql.jdbc.Driver";
    private String userName = "root"; 
    private String password = "anadolu232"; 
    private ResultSet res;
    /**
     * Creates new form ekle
     */
    public ekle() {
        initComponents();
        Statement st; 
        try {
            st = baglantiAc(); 
            res = st.executeQuery("SELECT * FROM  teshis"); 
        } catch (Exception ex) {
            
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
        }
    }
    public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);//bağlantı açılıyor           
        return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        //return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        //return conn.createStatement();
    }

    public void baglantiKapat() throws Exception {
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idtext = new javax.swing.JTextField();
        numara = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        adtext = new javax.swing.JTextField();
        tctext = new javax.swing.JTextField();
        tc = new javax.swing.JLabel();
        kan = new javax.swing.JLabel();
        kantext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        randevubilgi = new javax.swing.JLabel();
        rtarih = new javax.swing.JLabel();
        tarih = new javax.swing.JTextField();
        rsaat = new javax.swing.JLabel();
        saat = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        ilk = new javax.swing.JButton();
        sonraki = new javax.swing.JButton();
        onceki = new javax.swing.JButton();
        son = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        aratext = new javax.swing.JTextField();
        ara = new javax.swing.JButton();
        yardım = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        bayrak = new javax.swing.JLabel();
        bakan = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Randevu İşlemleri");

        numara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numara.setText("Hasta Numarası:");

        ad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ad.setText("Adı- Soyadı:");

        tc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tc.setText("TC Nosu:");

        kan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kan.setText("Kan Grubu:");

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));

        randevubilgi.setText("Randevu Bilgileri");

        rtarih.setText("R.Tarihi");

        rsaat.setText("R.Saati");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rtarih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rsaat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(randevubilgi)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(randevubilgi)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtarih)
                    .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rsaat)
                    .addComponent(saat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/kayıt.png"))); // NOI18N
        kaydet.setText("Randevuyu Kaydet");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/güncelle.png"))); // NOI18N
        guncelle.setText("Randevuyu Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        ilk.setText("İlk Hasta");
        ilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilkActionPerformed(evt);
            }
        });

        sonraki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni - Kopya (2).png"))); // NOI18N
        sonraki.setText("Sonraki Hasta");
        sonraki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonrakiActionPerformed(evt);
            }
        });

        onceki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni.png"))); // NOI18N
        onceki.setText("Önceki Hasta");
        onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncekiActionPerformed(evt);
            }
        });

        son.setText("Son Hasta");
        son.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        ara.setText("Hasta Ara");
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });

        yardım.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/arama.png"))); // NOI18N
        yardım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardımActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aratext)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(yardım, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ara, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(aratext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ara, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yardım, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/silme.png"))); // NOI18N
        sil.setText("Randevuyu Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        bayrak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N

        bakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N

        tittle.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tittle.setText("Randevu İşlemleri");

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni.png"))); // NOI18N
        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ilk)
                        .addGap(35, 35, 35)
                        .addComponent(sonraki)
                        .addGap(37, 37, 37)
                        .addComponent(onceki, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(son))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(numara)
                                .addGap(18, 18, 18)
                                .addComponent(idtext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(ad)
                                .addGap(18, 18, 18)
                                .addComponent(adtext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(kan)
                                .addGap(18, 18, 18)
                                .addComponent(kantext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(tc)
                                .addGap(18, 18, 18)
                                .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(geri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kaydet)
                                .addGap(17, 17, 17)
                                .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bayrak)
                .addGap(188, 188, 188)
                .addComponent(tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bakan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bayrak, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(tittle))
                    .addComponent(bakan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ilk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonraki)
                    .addComponent(onceki, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(son, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(numara))
                            .addComponent(idtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ad))
                            .addComponent(adtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(kan))
                            .addComponent(kantext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(tc))
                            .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelle))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sil)
                            .addComponent(geri)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
    try {
            res.moveToInsertRow();
            res.updateString("id",idtext.getText());
            res.updateString("adsoyad", adtext.getText());
            res.updateString("tc", tctext.getText());
            res.updateString("kangrubu", kantext.getText());
            res.updateString("teshis", "");
            res.updateString("ilaclar", "");
            res.updateString("receteno", "");
            res.updateString("tarih", tarih.getText());
            res.updateString("saat", saat.getText());
            res.insertRow();

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Randevu Eklenemedi", "HATA!", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_kaydetActionPerformed

    public void KayitGetir(String yon) {
        try {

            if (yon.equals("ileri")) {
                res.next();
            } else if (yon.equals("geri")) {
                res.previous();
            } else if (yon.equals("ilk")) {
                res.first();
            } else if (yon.equals("son")) {
                res.last();
            } 
             else if (yon.equals("mutlak")) {
                res.absolute(Integer.parseInt(aratext.getText()));
                

            }
            idtext.setText(res.getString("id"));
            adtext.setText(res.getString("adsoyad"));
            tctext.setText(res.getString("tc"));
            kantext.setText(res.getString("kangrubu"));
            tarih.setText(res.getString("tarih"));
            saat.setText(res.getString("saat"));
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Kayıt Mevcut Değil", "Kişiler Tablosu", JOptionPane.PLAIN_MESSAGE);
        }
        //KayitGetir("ilk");
    }
    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
    try {
            res.updateString("id", idtext.getText());
            res.updateString("adsoyad", adtext.getText());
            res.updateString("tc", tctext.getText());
            res.updateString("kangrubu", kantext.getText());
            res.updateString("tarih", tarih.getText());
            res.updateString("saat", saat.getText());
            
            res.updateRow();

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Randevu Eklenemedi", "HATA!", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void ilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilkActionPerformed
        KayitGetir("ilk");        // TODO add your handling code here:
    }//GEN-LAST:event_ilkActionPerformed

    private void sonrakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonrakiActionPerformed
        KayitGetir("ileri");        // TODO add your handling code here:
    }//GEN-LAST:event_sonrakiActionPerformed

    private void oncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncekiActionPerformed
        KayitGetir("geri");        // TODO add your handling code here:
    }//GEN-LAST:event_oncekiActionPerformed

    private void sonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonActionPerformed
        KayitGetir("son");        // TODO add your handling code here:
    }//GEN-LAST:event_sonActionPerformed

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        KayitGetir("mutlak");        // TODO add your handling code here:
    }//GEN-LAST:event_araActionPerformed

    private void yardımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardımActionPerformed
        yardım frame;
        frame=new yardım();
        frame.setVisible(true);

    }//GEN-LAST:event_yardımActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
    try {
            int onay = JOptionPane.showConfirmDialog(null, "Emin misiniz?", "Personel Tablosu", JOptionPane.YES_NO_OPTION);

            if (onay == 0) {    
                res.deleteRow();
                KayitGetir("ilk");
            } else {            

            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Kayıt Silinemedi", "Personel Tablosu", JOptionPane.PLAIN_MESSAGE);
        }   
    }//GEN-LAST:event_silActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
    randevu frame;
    frame = new randevu();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JTextField adtext;
    private javax.swing.JButton ara;
    private javax.swing.JTextField aratext;
    private javax.swing.JLabel bakan;
    private javax.swing.JLabel bayrak;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JTextField idtext;
    private javax.swing.JButton ilk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kan;
    private javax.swing.JTextField kantext;
    private javax.swing.JButton kaydet;
    private javax.swing.JLabel numara;
    private javax.swing.JButton onceki;
    private javax.swing.JLabel randevubilgi;
    private javax.swing.JLabel rsaat;
    private javax.swing.JLabel rtarih;
    private javax.swing.JTextField saat;
    private javax.swing.JButton sil;
    private javax.swing.JButton son;
    private javax.swing.JButton sonraki;
    private javax.swing.JTextField tarih;
    private javax.swing.JLabel tc;
    private javax.swing.JTextField tctext;
    private javax.swing.JLabel tittle;
    private javax.swing.JButton yardım;
    // End of variables declaration//GEN-END:variables
}
