/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diş.hastanesi.randevu.takip.programı;

/**
 *
 * @author Ahmed
 */
public class hastalıklar extends javax.swing.JFrame {

    /**
     * Creates new form hastalıklar
     */
    public hastalıklar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ağız ve Diş Hastalıkları Kodları");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 203, 17);

        jLabel2.setText("A001:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 73, 29, 14);

        jLabel3.setText("A002:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(25, 104, 29, 14);

        jLabel4.setText("A003:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(25, 135, 29, 14);

        jLabel5.setText("A004:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(25, 166, 29, 14);

        jLabel6.setText("A005:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(25, 197, 29, 14);

        jLabel7.setText("A006:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 228, 29, 14);

        jLabel8.setText("A007:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(25, 259, 29, 14);

        jLabel9.setText("A008:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(25, 290, 29, 14);

        jLabel10.setText("A009:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(25, 322, 29, 21);

        jLabel11.setText("A010:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(281, 70, 29, 14);

        jLabel12.setText("A011:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(281, 101, 29, 14);

        jLabel13.setText("A012:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(281, 132, 29, 14);

        jLabel14.setText("A013:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(281, 163, 29, 14);

        jLabel15.setText("A014:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(281, 194, 29, 14);

        jLabel16.setText("A015:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(281, 225, 29, 14);

        jLabel17.setText("A016:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(281, 256, 29, 14);

        jLabel18.setText("A017:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(281, 287, 29, 14);

        jTextField1.setEditable(false);
        jTextField1.setText("Uçuk");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(72, 67, 191, 20);

        jTextField2.setEditable(false);
        jTextField2.setText("Pamukçuk");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(72, 98, 191, 20);

        jTextField3.setEditable(false);
        jTextField3.setText("Siyah Kıllı Dil");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(72, 129, 191, 20);

        jTextField4.setEditable(false);
        jTextField4.setText("Aft");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(72, 160, 191, 20);

        jTextField5.setEditable(false);
        jTextField5.setText("Lökoplaki");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(72, 191, 191, 20);

        jTextField6.setEditable(false);
        jTextField6.setText("Liken Planus");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(72, 222, 191, 20);

        jTextField7.setEditable(false);
        jTextField7.setText("Harita Dil");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(72, 253, 191, 20);

        jTextField8.setEditable(false);
        jTextField8.setText("Ağız kanseri");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(72, 284, 191, 20);

        jTextField9.setEditable(false);
        jTextField9.setText("Temporomandibular Eklem Bozuklukları ");
        jPanel1.add(jTextField9);
        jTextField9.setBounds(72, 316, 191, 20);

        jTextField10.setEditable(false);
        jTextField10.setText("Yontulmuş Diş");
        jPanel1.add(jTextField10);
        jTextField10.setBounds(328, 67, 126, 20);

        jTextField11.setEditable(false);
        jTextField11.setText("Amalgam Lekesi");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(328, 98, 126, 20);

        jTextField12.setEditable(false);
        jTextField12.setText("Dişeti Hastalığı");
        jPanel1.add(jTextField12);
        jTextField12.setBounds(328, 129, 126, 20);

        jTextField13.setEditable(false);
        jTextField13.setText("Periodontitis");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(328, 160, 126, 20);

        jTextField14.setEditable(false);
        jTextField14.setText("Aspirin Yanığı");
        jPanel1.add(jTextField14);
        jTextField14.setBounds(328, 191, 126, 20);

        jTextField15.setEditable(false);
        jTextField15.setText("Çürükler ve Abseler");
        jPanel1.add(jTextField15);
        jTextField15.setBounds(328, 222, 126, 20);

        jTextField16.setEditable(false);
        jTextField16.setText("Ağız Kokusu");
        jPanel1.add(jTextField16);
        jTextField16.setBounds(328, 253, 126, 20);

        jTextField17.setEditable(false);
        jTextField17.setText("Lie Bump");
        jPanel1.add(jTextField17);
        jTextField17.setBounds(328, 284, 126, 20);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 0, 50, 49);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(486, 0, 50, 49);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hastalıklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hastalıklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hastalıklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hastalıklar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hastalıklar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
