/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diş.hastanesi.randevu.takip.programı;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed
 */
public class randevu extends javax.swing.JFrame {
    private Connection conn = null; 
    private String url = "jdbc:mysql://localhost:3306/";
    private String dbName = "hastane"; 
    private String driver = "com.mysql.jdbc.Driver";
    private String userName = "root"; 
    private String password = "anadolu232"; 
    private ResultSet res; 
    /**
     * Creates new form randevu
     */
    public randevu() {
        initComponents();
        Statement st; 
        try {
            st = baglantiAc(); 
            res = st.executeQuery("SELECT * FROM  ekle"); 
        } catch (Exception ex) {
            
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
        }
    }
    public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);//bağlantı açılıyor           
        return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        //return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        //return conn.createStatement();
    }

    public void baglantiKapat() throws Exception {
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kaydet = new javax.swing.JButton();
        sonbuton = new javax.swing.JButton();
        silbuton = new javax.swing.JButton();
        temizlebuton = new javax.swing.JButton();
        ilkbuton = new javax.swing.JButton();
        sonrakibuton = new javax.swing.JButton();
        oncekibuton = new javax.swing.JButton();
        randevulabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sifredegis = new javax.swing.JButton();
        geri = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        adtext = new javax.swing.JTextField();
        tctext = new javax.swing.JTextField();
        cinstext = new javax.swing.JTextField();
        haltext = new javax.swing.JTextField();
        kantext = new javax.swing.JTextField();
        annetext = new javax.swing.JTextField();
        babatext = new javax.swing.JTextField();
        saatlabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cins = new javax.swing.JLabel();
        tclabel = new javax.swing.JLabel();
        hekimlabel = new javax.swing.JLabel();
        tarihlabel = new javax.swing.JLabel();
        tarihtext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        kimlik = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tellabel = new javax.swing.JLabel();
        teltext = new javax.swing.JTextField();
        mesleklabel = new javax.swing.JLabel();
        meslektext = new javax.swing.JTextField();
        maillabel = new javax.swing.JLabel();
        adreslabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adrestext = new javax.swing.JTextArea();
        illabel = new javax.swing.JLabel();
        iltext = new javax.swing.JTextField();
        ilcelabel = new javax.swing.JLabel();
        ilcetext = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        mailtext = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        aratext = new javax.swing.JTextField();
        ara = new javax.swing.JButton();
        yardım = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        ekle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Randevu Kayıt");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/kayıt.png"))); // NOI18N
        kaydet.setText("Hastayı Kaydet");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        sonbuton.setText("Son Hastayı Görüntüle");
        sonbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonbutonActionPerformed(evt);
            }
        });

        silbuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/silme.png"))); // NOI18N
        silbuton.setText("Hastayı Sil");
        silbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silbutonActionPerformed(evt);
            }
        });

        temizlebuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/sill.png"))); // NOI18N
        temizlebuton.setText("Ekranı Temizle");
        temizlebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizlebutonActionPerformed(evt);
            }
        });

        ilkbuton.setText("İlk Hastayı Görüntüle");
        ilkbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilkbutonActionPerformed(evt);
            }
        });

        sonrakibuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni - Kopya (2).png"))); // NOI18N
        sonrakibuton.setText("Sonraki Hastayı Görüntüle");
        sonrakibuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonrakibutonActionPerformed(evt);
            }
        });

        oncekibuton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni.png"))); // NOI18N
        oncekibuton.setText("Önceki Hastayı Görüntüle");
        oncekibuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncekibutonActionPerformed(evt);
            }
        });

        randevulabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        randevulabel.setText("Hastane Randevu Sistemi");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N

        sifredegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/şifrede.png"))); // NOI18N
        sifredegis.setText("Şifre İşlemleri");
        sifredegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifredegisActionPerformed(evt);
            }
        });

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geri2.png"))); // NOI18N
        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/güncelle.png"))); // NOI18N
        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        cinstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinstextActionPerformed(evt);
            }
        });

        kantext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kantextActionPerformed(evt);
            }
        });

        saatlabel.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        saatlabel.setText("Baba Adı:");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        jLabel5.setText("Anne Adı:");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        jLabel4.setText("Kan Grubu:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        jLabel3.setText("Medeni Hali:");

        cins.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        cins.setText("Cinsiyeti:");

        tclabel.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        tclabel.setText(" TC No:");

        hekimlabel.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        hekimlabel.setText("Adı-Soyadı:");

        tarihlabel.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        tarihlabel.setText("Doğum Tarihi:");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        jLabel7.setText("Hasta Numarası:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tarihlabel)
                    .addComponent(hekimlabel)
                    .addComponent(saatlabel)
                    .addComponent(tclabel)
                    .addComponent(cins)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(babatext, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(annetext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(haltext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idtext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tctext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adtext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cinstext)
                    .addComponent(kantext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tarihtext))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hekimlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tclabel)
                    .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cins)
                    .addComponent(cinstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(haltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kantext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(babatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saatlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihlabel)
                    .addComponent(tarihtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        kimlik.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kimlik.setText("Kimlik Bilgileri");

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        tellabel.setText("Telefon:");

        mesleklabel.setText("Mesleği:");

        maillabel.setText("E-mail:");

        adreslabel.setText("Adres:");

        adrestext.setColumns(20);
        adrestext.setRows(5);
        jScrollPane1.setViewportView(adrestext);

        illabel.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        illabel.setText("İl:");

        iltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iltextActionPerformed(evt);
            }
        });

        ilcelabel.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        ilcelabel.setText("İlçe:");

        mailtext.setColumns(20);
        mailtext.setRows(5);
        jScrollPane2.setViewportView(mailtext);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tellabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(maillabel)
                        .addComponent(mesleklabel)
                        .addComponent(adreslabel)
                        .addComponent(illabel)
                        .addComponent(ilcelabel)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meslektext)
                    .addComponent(teltext)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(iltext)
                    .addComponent(ilcetext))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tellabel)
                    .addComponent(teltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesleklabel)
                    .addComponent(meslektext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maillabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adreslabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(illabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilcetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilcelabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("İletişim Bilgileri");

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));

        ara.setText("Hasta Ara");
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });

        yardım.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/arama.png"))); // NOI18N
        yardım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardımActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(yardım, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(aratext, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aratext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yardım, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/oturumu.jpg"))); // NOI18N
        cikis.setText("Oturumu Kapat");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/ekle.png"))); // NOI18N
        ekle.setText("Randevu Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(kimlik)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(silbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(temizlebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(sifredegis, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ilkbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sonrakibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oncekibuton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sonbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(randevulabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(randevulabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ekle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sonrakibuton)
                        .addComponent(oncekibuton)
                        .addComponent(sonbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ilkbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kimlik)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(silbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(guncelle)
                        .addGap(1, 1, 1)
                        .addComponent(temizlebuton)
                        .addGap(1, 1, 1)
                        .addComponent(sifredegis)
                        .addGap(19, 19, 19)
                        .addComponent(cikis))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iltextActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
    try {  
            //res.getRow();
            res.moveToInsertRow(); 
            res.updateString("id", idtext.getText());
            res.updateString("ad", adtext.getText()); 
            res.updateString("tc", tctext.getText());
            res.updateString("cinsiyet", cinstext.getText());
            res.updateString("hal", haltext.getText());
            res.updateString("kan grubu", kantext.getText());
            res.updateString("anne adı", annetext.getText());
            res.updateString("baba adı", babatext.getText());
            res.updateString("dogum", tarihtext.getText());
            res.updateString("telefon", teltext.getText());
            res.updateString("meslek", meslektext.getText());
            res.updateString("mail", mailtext.getText());
            res.updateString("adres", adrestext.getText());
            res.updateString("il", iltext.getText());
            res.updateString("ilce", ilcetext.getText());
             res.insertRow();
            
            
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Hasta Eklenemedi", "HATA!", JOptionPane.PLAIN_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_kaydetActionPerformed
public void KayitGetir(String yon) {
        try {

            if (yon.equals("ileri")) {
                res.next();
            } else if (yon.equals("geri")) {
                res.previous();
            } else if (yon.equals("ilk")) {
                res.first();
            } else if (yon.equals("son")) {
                res.last();
            } 
             else if (yon.equals("mutlak")) {
                res.absolute(Integer.parseInt(aratext.getText()));
                

            }
            idtext.setText(res.getString("id"));
            adtext.setText(res.getString("ad"));
            tctext.setText(res.getString("tc"));
            cinstext.setText(res.getString("cinsiyet"));
            haltext.setText(res.getString("hal"));
            kantext.setText(res.getString("kan grubu"));
            annetext.setText(res.getString("anne adı"));
            babatext.setText(res.getString("baba adı"));
            tarihtext.setText(res.getString("dogum"));
            teltext.setText(res.getString("telefon"));
            meslektext.setText(res.getString("meslek"));
            mailtext.setText(res.getString("mail"));
            adrestext.setText(res.getString("adres"));
            iltext.setText(res.getString("il"));
            ilcetext.setText(res.getString("ilce"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Kayıt Mevcut Değil", "Kişiler Tablosu", JOptionPane.PLAIN_MESSAGE);
        }

    }
    
    private void sonbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonbutonActionPerformed
        KayitGetir("son");
                   // TODO add your handling code here:
    }//GEN-LAST:event_sonbutonActionPerformed

    private void ilkbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilkbutonActionPerformed
    KayitGetir("ilk");        // TODO add your handling code here:
    }//GEN-LAST:event_ilkbutonActionPerformed

    private void sonrakibutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonrakibutonActionPerformed
    KayitGetir("ileri");        // TODO add your handling code here:
    }//GEN-LAST:event_sonrakibutonActionPerformed

    private void oncekibutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncekibutonActionPerformed
    KayitGetir("geri");        // TODO add your handling code here:
    }//GEN-LAST:event_oncekibutonActionPerformed

    private void temizlebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizlebutonActionPerformed
    ilcetext.setText("");        
    adtext.setText("");
    tarihtext.setText("");
    babatext.setText("");  
    annetext.setText("");
    tctext.setText("");
    teltext.setText("");
    meslektext.setText("");
    adrestext.setText("");
    mailtext.setText("");
    iltext.setText("");
    idtext.setText("");
    cinstext.setText("");
    haltext.setText("");
    kantext.setText("");
    
    
    }//GEN-LAST:event_temizlebutonActionPerformed

    private void sifredegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifredegisActionPerformed
    sifredegis frame;
    frame=new sifredegis();
    frame.setVisible(true);
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_sifredegisActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
    hasta frame;
    frame=new hasta();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_geriActionPerformed

    private void silbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silbutonActionPerformed
    try {
            int onay = JOptionPane.showConfirmDialog(null, "Emin misiniz?", "Personel Tablosu", JOptionPane.YES_NO_OPTION);

            if (onay == 0) {    
                res.deleteRow();
                KayitGetir("ilk");
            } else {            

            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Kayıt Silinemedi", "Personel Tablosu", JOptionPane.PLAIN_MESSAGE);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_silbutonActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
    Giris frame;
    frame= new Giris();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_cikisActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
    try {
            
           
           res.updateString("ad", adtext.getText()); 
            res.updateString("tc", tctext.getText());
            res.updateString("cinsiyet", cinstext.getText());
            res.updateString("hal", haltext.getText());
            res.updateString("kan grubu", kantext.getText());
            res.updateString("anne adı", annetext.getText());
            res.updateString("baba adı", babatext.getText());
            res.updateString("dogum", tarihtext.getText());
            res.updateString("telefon", teltext.getText());
            res.updateString("meslek", meslektext.getText());
            res.updateString("mail", mailtext.getText());
            res.updateString("adres", adrestext.getText());
            res.updateString("il", iltext.getText());
            res.updateString("ilce", ilcetext.getText());
           
           res.updateRow();
        }
        catch (SQLException ex) 
        {
            JOptionPane.showConfirmDialog(null, "Kayıt Güncellenemedi", "Personel Tablosu", JOptionPane.PLAIN_MESSAGE);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_guncelleActionPerformed

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
    KayitGetir("mutlak");        // TODO add your handling code here:
    }//GEN-LAST:event_araActionPerformed

    private void yardımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardımActionPerformed
    yardım frame;
    frame=new yardım();
    frame.setVisible(true);
    }//GEN-LAST:event_yardımActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
    ekle frame;
    frame=new ekle();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_ekleActionPerformed

    private void cinstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinstextActionPerformed

    private void kantextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kantextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kantextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(randevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new randevu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adreslabel;
    private javax.swing.JTextArea adrestext;
    private javax.swing.JTextField adtext;
    private javax.swing.JTextField annetext;
    private javax.swing.JButton ara;
    private javax.swing.JTextField aratext;
    private javax.swing.JTextField babatext;
    private javax.swing.JButton cikis;
    private javax.swing.JLabel cins;
    private javax.swing.JTextField cinstext;
    private javax.swing.JButton ekle;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JTextField haltext;
    private javax.swing.JLabel hekimlabel;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel ilcelabel;
    private javax.swing.JTextField ilcetext;
    private javax.swing.JButton ilkbuton;
    private javax.swing.JLabel illabel;
    private javax.swing.JTextField iltext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kantext;
    private javax.swing.JButton kaydet;
    private javax.swing.JLabel kimlik;
    private javax.swing.JLabel maillabel;
    private javax.swing.JTextArea mailtext;
    private javax.swing.JLabel mesleklabel;
    private javax.swing.JTextField meslektext;
    private javax.swing.JButton oncekibuton;
    private javax.swing.JLabel randevulabel;
    private javax.swing.JLabel saatlabel;
    private javax.swing.JButton sifredegis;
    private javax.swing.JButton silbuton;
    private javax.swing.JButton sonbuton;
    private javax.swing.JButton sonrakibuton;
    private javax.swing.JLabel tarihlabel;
    private javax.swing.JTextField tarihtext;
    private javax.swing.JLabel tclabel;
    private javax.swing.JTextField tctext;
    private javax.swing.JLabel tellabel;
    private javax.swing.JTextField teltext;
    private javax.swing.JButton temizlebuton;
    private javax.swing.JButton yardım;
    // End of variables declaration//GEN-END:variables
}
