/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diş.hastanesi.randevu.takip.programı;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class teshis extends javax.swing.JFrame {
    private Connection conn = null; 
    private String url = "jdbc:mysql://localhost:3306/";
    private String dbName = "hastane"; 
    private String driver = "com.mysql.jdbc.Driver";
    private String userName = "root"; 
    private String password = "anadolu232"; 
    private ResultSet res;
    /**
     * Creates new form teshis
     */
    public teshis() {
        initComponents();
        Statement st; 
        try {
            st = baglantiAc(); 
            res = st.executeQuery("SELECT * FROM  teshis"); 
        } catch (Exception ex) {
            
            JOptionPane.showConfirmDialog(null, "Bağlantı Başarısız", "MySQL Bağlantısı", JOptionPane.PLAIN_MESSAGE);
        }
    }
    public Statement baglantiAc() throws Exception {
        Class.forName(driver).newInstance();
        conn = DriverManager.getConnection(url + dbName, userName, password);//bağlantı açılıyor           
        return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        //return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
        //return conn.createStatement();
    }

    public void baglantiKapat() throws Exception {
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        teşhis = new javax.swing.JLabel();
        teshistext = new javax.swing.JTextField();
        idtext = new javax.swing.JTextField();
        adtext = new javax.swing.JTextField();
        recete = new javax.swing.JLabel();
        kayıt = new javax.swing.JButton();
        kantext = new javax.swing.JTextField();
        recetetext = new javax.swing.JTextField();
        kan = new javax.swing.JLabel();
        kaydet = new javax.swing.JButton();
        numara = new javax.swing.JLabel();
        tctext = new javax.swing.JTextField();
        tc = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        ilk = new javax.swing.JButton();
        sonraki = new javax.swing.JButton();
        onceki = new javax.swing.JButton();
        son = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        info = new javax.swing.JButton();
        bayrak = new javax.swing.JLabel();
        bakan7 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        aratext = new javax.swing.JTextField();
        ara = new javax.swing.JButton();
        yardım = new javax.swing.JButton();
        geri = new javax.swing.JButton();
        ilaclar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilactext = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarih = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        saat = new javax.swing.JTextField();
        sıradaki = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hastanın Durumu");

        teşhis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        teşhis.setText("Teşhis:");

        recete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        recete.setText("E-Reçete No:");

        kayıt.setText("Teşhisi Kaydet");
        kayıt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtActionPerformed(evt);
            }
        });

        kan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kan.setText("Kan Grubu:");

        kaydet.setText("E-Reçete Numarası Oluştur");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        numara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numara.setText("Hasta Numarası:");

        tc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tc.setText("TC Nosu:");

        ad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ad.setText("Adı- Soyadı:");

        ilk.setText("İlk Hasta");
        ilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilkActionPerformed(evt);
            }
        });

        sonraki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni - Kopya (2).png"))); // NOI18N
        sonraki.setText("Sonraki Hasta");
        sonraki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonrakiActionPerformed(evt);
            }
        });

        onceki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geriyeni.png"))); // NOI18N
        onceki.setText("Önceki Hasta");
        onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncekiActionPerformed(evt);
            }
        });

        son.setText("Son Hasta");
        son.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonActionPerformed(evt);
            }
        });

        guncelle.setText("Teşhisi Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/info.png"))); // NOI18N
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        bayrak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/bayrak.jpg"))); // NOI18N

        bakan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/saglıkbakanlığı.png"))); // NOI18N

        tittle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tittle.setText("Hastanın Durumu");

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        ara.setText("Hasta Ara");
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });

        yardım.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/arama.png"))); // NOI18N
        yardım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardımActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(aratext, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(yardım, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(aratext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ara, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yardım, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/geri2.png"))); // NOI18N
        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        ilaclar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ilaclar.setText("Verilen İlaçlar:");

        ilactext.setColumns(20);
        ilactext.setRows(5);
        jScrollPane1.setViewportView(ilactext);

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));

        jLabel5.setText("Randevu Bilgileri");

        jLabel6.setText("R.Tarihi");

        tarih.setEditable(false);

        jLabel7.setText("R.Saati");

        saat.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(42, 42, 42))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(saat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sıradaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diş/hastanesi/randevu/takip/programı/simgeler/tablo.jpg"))); // NOI18N
        sıradaki.setText("Sıradaki Hastaları Göster");
        sıradaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sıradakiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bayrak, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geri)
                .addGap(74, 74, 74)
                .addComponent(tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(sıradaki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bakan7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numara)
                                    .addComponent(ad)
                                    .addComponent(tc)
                                    .addComponent(kan)
                                    .addComponent(teşhis)
                                    .addComponent(ilaclar))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idtext)
                                    .addComponent(adtext)
                                    .addComponent(tctext)
                                    .addComponent(kantext)
                                    .addComponent(teshistext)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(recete)
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(recetetext))))
                        .addGap(18, 18, 18)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ilk)
                        .addGap(53, 53, 53)
                        .addComponent(sonraki)
                        .addGap(39, 39, 39)
                        .addComponent(onceki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(son)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kayıt)
                        .addGap(32, 32, 32)
                        .addComponent(guncelle)
                        .addGap(37, 37, 37)
                        .addComponent(kaydet)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bayrak, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tittle))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sıradaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(bakan7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonraki)
                    .addComponent(onceki)
                    .addComponent(son, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numara)
                            .addComponent(idtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad)
                            .addComponent(adtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc)
                            .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kan)
                            .addComponent(kantext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teşhis)
                            .addComponent(teshistext)
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ilaclar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recete)
                            .addComponent(recetetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle)
                    .addComponent(kayıt))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        try {
            res.updateString("id", idtext.getText());
            res.updateString("adsoyad", adtext.getText());
            res.updateString("tc", tctext.getText());
            res.updateString("kangrubu", kantext.getText());
            res.updateString("teshis", teshistext.getText());
            res.updateString("ilaclar", ilactext.getText());
            res.updateString("receteno", recetetext.getText());
            res.updateRow();

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Teşhis Eklenemedi", "HATA!", JOptionPane.PLAIN_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_guncelleActionPerformed

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        KayitGetir("mutlak");        // TODO add your handling code here:
    }//GEN-LAST:event_araActionPerformed

    private void sonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonActionPerformed
        KayitGetir("son");        // TODO add your handling code here:
    }//GEN-LAST:event_sonActionPerformed

    private void oncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncekiActionPerformed
        KayitGetir("geri");        // TODO add your handling code here:
    }//GEN-LAST:event_oncekiActionPerformed

    private void sonrakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonrakiActionPerformed
        KayitGetir("ileri");        // TODO add your handling code here:
    }//GEN-LAST:event_sonrakiActionPerformed

    private void ilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilkActionPerformed
        KayitGetir("ilk");        // TODO add your handling code here:
    }//GEN-LAST:event_ilkActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        int Sayi = (int) (Math.random()*9999999);
        recetetext.setText(Integer.toString(Sayi));
    }//GEN-LAST:event_kaydetActionPerformed

    private void kayıtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtActionPerformed
        try {
            res.moveToInsertRow();
            res.updateString("id", idtext.getText());
            res.updateString("adsoyad", adtext.getText());
            res.updateString("tc", tctext.getText());
            res.updateString("kangrubu", kantext.getText());
            res.updateString("teshis", teshistext.getText());
            res.updateString("ilaclar", ilactext.getText());
            res.updateString("receteno", recetetext.getText());
            res.insertRow();

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Teşhis Eklenemedi", "HATA!", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_kayıtActionPerformed

    private void yardımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardımActionPerformed
    yardım frame;
    frame=new yardım();
    frame.setVisible(true);
    
    }//GEN-LAST:event_yardımActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
    hastalıklar frame;
    frame = new hastalıklar();
    frame.setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
    doktorsayfa frame;
    frame = new doktorsayfa();
    frame.setVisible(true);
    dispose();
    }//GEN-LAST:event_geriActionPerformed

    private void sıradakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sıradakiActionPerformed
        tablo frame;
        frame= new tablo();
        frame.setVisible(true);
    }//GEN-LAST:event_sıradakiActionPerformed

    public void KayitGetir(String yon) {
        try {

            if (yon.equals("ileri")) {
                res.next();
            } else if (yon.equals("geri")) {
                res.previous();
            } else if (yon.equals("ilk")) {
                res.first();
            } else if (yon.equals("son")) {
                res.last();
            } 
             else if (yon.equals("mutlak")) {
                res.absolute(Integer.parseInt(aratext.getText()));
                

            }
            idtext.setText(res.getString("id"));
            adtext.setText(res.getString("adsoyad"));
            tctext.setText(res.getString("tc"));
            kantext.setText(res.getString("kangrubu"));
            teshistext.setText(res.getString("teshis"));
            ilactext.setText(res.getString("ilaclar"));
            recetetext.setText(res.getString("receteno"));
            tarih.setText(res.getString("tarih"));
            saat.setText(res.getString("saat"));
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Kayıt Mevcut Değil", "Kişiler Tablosu", JOptionPane.PLAIN_MESSAGE);
        }
        //KayitGetir("ilk");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teshis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teshis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teshis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teshis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teshis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JTextField adtext;
    private javax.swing.JButton ara;
    private javax.swing.JTextField aratext;
    private javax.swing.JLabel bakan7;
    private javax.swing.JLabel bayrak;
    private javax.swing.JButton geri;
    private javax.swing.JButton guncelle;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel ilaclar;
    private javax.swing.JTextArea ilactext;
    private javax.swing.JButton ilk;
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kan;
    private javax.swing.JTextField kantext;
    private javax.swing.JButton kaydet;
    private javax.swing.JButton kayıt;
    private javax.swing.JLabel numara;
    private javax.swing.JButton onceki;
    private javax.swing.JLabel recete;
    private javax.swing.JTextField recetetext;
    private javax.swing.JTextField saat;
    private javax.swing.JButton son;
    private javax.swing.JButton sonraki;
    private javax.swing.JButton sıradaki;
    private javax.swing.JTextField tarih;
    private javax.swing.JLabel tc;
    private javax.swing.JTextField tctext;
    private javax.swing.JTextField teshistext;
    private javax.swing.JLabel teşhis;
    private javax.swing.JLabel tittle;
    private javax.swing.JButton yardım;
    // End of variables declaration//GEN-END:variables
}
